import Navbar from './component/Navbar/Navbar'
import './globals.css'

import '/public/mad/stylesheet.css'

export const metadata = {
  title: 'Talk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
